version: '3.8'

services:
  db:
    build: .
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./imdb_data:/imdb_data
